create database theRanch;

use theRanch;

create table artistas (
idArtista int primary key auto_increment,
nome varchar(45),
banner varchar(100),
biografia text,
dtNasc varchar(80),
localNasc varchar(80),
atividade varchar(50),
algumasMusicas varchar(200),
foto varchar(100),
principalHit varchar(100),
spotify varchar(45),
youtube varchar(45) 
);

-- Inserindo cantores universitários - solo
insert into artistas values
(default, 
'Cristiano Araújo', 
'style/assets/images/cantor_específico/universitarios_solo/cristianoAraujo.png',
'Cristiano Araújo nasceu em Goiânia, Goiás, no dia 24 de janeiro de 1986 numa família de músicos. Com quatro anos já gostava de cantar e segundo seu pai, José Reis de Araújo, mostrava ser afinado. Com seis anos ganhou seu primeiro violão e com nove anos começou a se apresentava em público.
    Com 13 anos gravou seu primeiro CD. Sua carreira deslanchou em 2011, a partir da música “Efeitos”. Com mais de 250 milhões de acessos em seu canal oficial no YouTube. Cristiano gravou dois álbuns em estúdio e três ao vivo, além de três DVDs. Cumpria uma agenda de 280 shows por ano. Entre seus sucessos destacam-se: "Efeitos", "Bara Bara", "Você Mudou", "Maus Bocados", "Cê Que Sabe", "Hoje Eu Tô Terrível".
     No dia 24 de junho de 2015, ao regressar de um show que fez na cidade de Itumbiara, estava deitado no banco traseiro de sua Ranger Rouver, ao lado de sua namorada Allana Moraes, de 19 anos, quando, na BR – 153, o carro saiu da pista e capotou. Allana teve morte imediata. Cristiano chegou a ser socorrido, mas não resistiu. Faleceu com apenas 29 anos, no auge do sucesso de sua carreira musical.',
'24 de Janeiro de 1986',
'Goiânia-GO',
'1995 - 2015',
'Efeitos - 2011 / Maus Bocados - 2013 / Cê Que Sabe? - 2014',
'style/assets/images/fotos_cantores/universitario_solo/cristianoAraujo.png',
'Caso Indefinido - 2013',
'+139 milhões',
'+383 milhões'),
(default, 'Enzo Rabelo',
'style/assets/images/cantor_específico/universitarios_solo/enzoRabelo.png',
'Enzo Rabelo é um jovem cantor e compositor brasileiro que vem conquistando o cenário musical com seu talento precoce. Filho do cantor Bruno, da dupla Bruno & Marrone, Enzo iniciou sua carreira artística aos 10 anos, em 2018, ao publicar vídeos cantando no YouTube. Seu estilo musical transita entre o sertanejo romântico e o pop, cativando uma ampla audiência. Com uma voz marcante e presença de palco, ele rapidamente ganhou notoriedade, acumulando milhões de visualizações em suas músicas. Enzo já colaborou com artistas renomados como Zé Felipe e Gusttavo Lima, ampliando ainda mais seu alcance. Em 2020, lançou seu primeiro DVD ao vivo, gravado em Uberlândia, Minas Gerais. Desde então, continua ativo na música, lançando novos projetos e singles que reforçam sua posição como uma das promessas da nova geração do sertanejo. Além da música, Enzo também é influente nas redes sociais, compartilhando sua rotina e novidades com seus seguidores. Seu carisma e dedicação indicam uma carreira promissora pela frente.',
'24 de Outubro de 2024',
'Goianápolis – GO',
'2018 - Presente',
'Meio caminho andado - 2022 / Perfeitinha - 2023 / 2% - 2023',
'style/assets/images/fotos_cantores/universitario_solo/enzoRabelo.png',
'Tijolinho por Tijolinho (feat. Zé Felipe) - 2018',
'+63 milhões',
'+435 milhões'),
(default, 'Felipe Araújo',
'style/assets/images/cantor_específico/universitarios_solo/felipeAraujo.png',
'Felipe Araújo é um cantor e compositor brasileiro de sertanejo, conhecido por sua voz marcante e por emplacar vários hits nas paradas. Ele é irmão do saudoso Cristiano Araújo, cantor que faleceu em 2015. Inspirado pelo irmão e pela paixão pela música, Felipe decidiu seguir carreira solo ainda em 2015. Seu estilo mistura o sertanejo romântico com toques modernos do sertanejo universitário. Com carisma e presença de palco, ele rapidamente conquistou o público. Seu primeiro grande sucesso foi “A Mala é Falsa”, parceria com Henrique & Juliano. Desde então, lançou vários singles que se destacaram nas rádios e plataformas digitais. Felipe também é conhecido por suas apresentações emocionantes e pelo cuidado com sua imagem artística. Com uma trajetória sólida, ele já se consolidou como um dos nomes fortes da nova geração do sertanejo. Atualmente, segue ativo na música, lançando novos projetos e turnês.',
'02 de julho de 1995',
'Goiânia - GO',
'2015 – Presente',
'A Mala é Falsa – 2016 / Amor da Sua Cama – 2017 / Espaçosa Demais – 2019 ',
'style/assets/images/fotos_cantores/universitario_solo/felipeAraujo.png',
'Atrasadinha (feat. Ferrugem) - 2018',
'+275 milhões',
'+500 milhões'),
(default, 'Gabriel Diniz',
'style/assets/images/cantor_específico/universitarios_solo/gabrielDiniz.png',
'Gabriel Diniz, nascido José Gabriel de Souza Diniz, foi um cantor e compositor brasileiro que se destacou no cenário musical nordestino. Nascido em Campo Grande, Mato Grosso do Sul, mudou-se ainda criança para João Pessoa, na Paraíba, onde iniciou sua trajetória musical. Durante a faculdade de engenharia elétrica, formou uma banda de garagem com amigos, o que o levou a ingressar em grupos como Capim com Mel e Cavaleiros do Forró. Em 2011, lançou sua própria banda, Forró na Farra, e posteriormente seguiu carreira solo. Seu estilo musical era uma fusão de forró com elementos de swingueira, destacando-se pela energia e carisma nas apresentações. Em 2018, alcançou sucesso nacional com o hit “Jenifer”, que se tornou a música mais tocada no Carnaval de 2019. Infelizmente, sua carreira promissora foi interrompida por um trágico acidente aéreo em maio de 2019. Gabriel deixou um legado marcante na música brasileira, sendo lembrado por sua alegria e talento.',
'18 de outubro de 1990',
'Campo Grande - MS',
'2008 – 2019',
'Safadezinha - 2016 / Acabou Acabou - 2017 / Paraquedas - 2018 /',
'style/assets/images/fotos_cantores/universitario_solo/gabrielDiniz.png',
'Jenifer - 2019',
'+97 milhões',
'+372 milhões'),
(default, 'Gustavo Mioto',
'style/assets/images/cantor_específico/universitarios_solo/gustavoMioto.png',
'Gustavo Pieroni Mioto é um cantor, compositor e multi-instrumentista brasileiro, nascido em Votuporanga, interior de São Paulo. Desde pequeno, demonstrou interesse pela música, compondo sua primeira canção aos 10 anos. Em 2012, lançou seu álbum de estreia, Fora de Moda, iniciando sua carreira profissional. Ganhou notoriedade nacional com o hit “Impressionando os Anjos” em 2016, consolidando-se no cenário sertanejo. Seu estilo musical transita entre o sertanejo romântico e o pop, com letras que abordam temas como amor e relacionamentos. Em 2020, sua música “Com ou Sem Mim” foi a mais tocada nas rádios brasileiras. Ao longo de sua carreira, colaborou com diversos artistas renomados, como Anitta e Jorge & Mateus. Além de cantor, Mioto é conhecido por sua habilidade em tocar instrumentos como violão, guitarra, piano e banjo. Atualmente, continua ativo na música, lançando novos projetos e singles. Seu talento e carisma o tornam uma das principais vozes da nova geração do sertanejo.',
'12 de março de 1997',
'Votuporanga - SP',
'2012 – Presente',
'Impressionando os Anjos – 2016 / Coladinha em Mim (feat. Anitta) – 2017 / Eu Gosto Assim (feat. Mari Fernandez) – 2022',
'style/assets/images/fotos_cantores/universitario_solo/gustavoMioto.png',
'Com ou Sem Mim - 2020',
'+179 milhões',
'+305 milhões'),
(default, 'Gusttavo Lima',
'style/assets/images/cantor_específico/universitarios_solo/gusttavoLima.png',
'Gusttavo Lima, nome artístico de Nivaldo Batista Lima, nasceu em Presidente Olegário, Minas Gerais, em 3 de setembro de 1989. Desde cedo, demonstrou interesse pela música, aprendendo a tocar diversos instrumentos de forma autodidata. Aos nove anos, saiu de casa para seguir carreira musical, formando uma banda com os irmãos. Em 2009, iniciou sua carreira solo, mas foi em 2011 que alcançou fama nacional com o hit “Balada (Tchê Tchê Rere)”. Conhecido por sua voz marcante e presença de palco, Gusttavo consolidou-se como um dos principais nomes do sertanejo universitário. Além de cantor, é compositor, produtor musical e empresário. Seu estilo musical transita entre o sertanejo tradicional e o romântico, com influências de arrocha e bachata. Ao longo de sua carreira, lançou diversos álbuns e DVDs de sucesso. Atualmente, continua ativo na música, realizando turnês e lançando novos projetos. Seu carisma e talento o tornaram uma referência no cenário musical brasileiro.',
'3 de setembro de 1989',
'Presidente Olegário - MG',
'2009 – Presente',
'Apelido Carinhoso – 2017 / Apelido Carinhoso - 2019 / Bloqueado – 2021',
'style/assets/images/fotos_cantores/universitario_solo/gusttavoLima.png',
'Balada - 2012',
'+239 milhões',
'+338 milhões'),
(default, 'Hugo Henrique',
'style/assets/images/cantor_específico/universitarios_solo/hugoHenrique.png',
'Hugo Henrique é um cantor e compositor brasileiro nascido em 1º de junho de 2004, em São Paulo. Ele começou sua trajetória musical aos 5 anos, incentivado por sua tia, e logo passou a se apresentar em programas de TV regionais. Sua grande inspiração foi o cantor Cristiano Araújo, com quem teve a oportunidade de dividir o palco ainda criança. Aos 9 anos, lançou seu primeiro CD, “Anjo Sem Asas”, com participações de Thiago Brava e Cristiano Araújo. Em 2017, gravou o DVD “Só Dessa Vez”, que contou com colaborações de Marília Mendonça, Maiara & Maraisa e Naiara Azevedo. Além de intérprete, Hugo é um compositor talentoso, tendo escrito músicas para artistas como Marília Mendonça e Murilo Huff. Seu estilo mistura o sertanejo romântico com influências pop, destacando-se pela voz marcante e letras emotivas. Em 2024, lançou o álbum “Autoral”, reunindo composições próprias e regravações de sucessos seus na voz de outros artistas. Atualmente, Hugo continua ativo na música, realizando shows e lançando novos projetos. Seu carisma e talento o consolidam como uma das promessas da nova geração do sertanejo.',
'1º de junho de 2004',
'São Paulo - SP',
'2013 – Presente',
'Só Falta Você Aceitar – 2017 / Dia 1 - 2024 / Terminou Pra Quê? – 2025',
'style/assets/images/fotos_cantores/universitario_solo/hugoHenrique.png',
'Mala - 2017',
'+26 milhões',
'+76 milhões'),
(default, 'Lauana Prado',
'style/assets/images/cantor_específico/universitarios_solo/lauanaPrado.png',
'Lauana Prado, nascida Mayara Lauana Pereira e Vieira do Prado, é uma cantora e compositora brasileira de música sertaneja. Natural de Goiânia, cresceu em Araguaína, Tocantins, onde começou a cantar em bares locais. Participou de programas de calouros como “Jovens Talentos” e “The Voice Brasil”, utilizando o nome artístico Mayara Prado. Em 2014, lançou seu primeiro EP, mas foi em 2018, já como Lauana Prado, que alcançou sucesso nacional com a música “Cobaia”. Desde então, lançou álbuns como “Verdade”, “Livre” e “Natural”, este último indicado ao Grammy Latino. Seu estilo mistura sertanejo com influências de pop e MPB, destacando-se por sua voz potente e letras emotivas. Lauana também é reconhecida por regravações de clássicos sertanejos em projetos como “Raiz” e “Raiz Goiânia”. Em 2024, lançou o álbum “Transcende”, gravado ao vivo no Ginásio do Ibirapuera, com participações de artistas renomados. Além da música, é conhecida por sua autenticidade e representatividade no cenário sertanejo. Atualmente, continua ativa na música, realizando shows e lançando novos projetos.',
'25 de maio de 1989',
'Goiânia - GO',
'2011 – Presente',
'Viva Voz – 2020 / Terminou Com Calma – 2022 / Escrito nas Estrelas – 2023',
'style/assets/images/fotos_cantores/universitario_solo/lauanaPrado.png',
'Cobaia (feat. Maiara & Maraisa) - 2018',
'+269 milhões',
'+609 milhões'),
(default, 'Lucas Lucco',
'style/assets/images/cantor_específico/universitarios_solo/lucasLucco.png',
'Lucas Corrêa de Oliveira, conhecido artisticamente como Lucas Lucco, é um cantor, compositor e ator brasileiro. Natural de Patrocínio, Minas Gerais, iniciou sua carreira musical em 2007 com o trio sertanejo Skypiras. Em 2011, seguiu carreira solo, ganhando destaque com a música “Pra Te Fazer Lembrar”. Além da música, atuou em novelas como “Malhação” e participou de reality shows. Seu estilo musical transita entre o sertanejo universitário, pop e funk, com letras que abordam temas como amor e relacionamentos. Lucas também é conhecido por sua atuação como modelo e empresário no ramo fitness. Lançou álbuns como “Nem Te Conto” e “O Destino”, consolidando-se no cenário musical brasileiro. Parcerias com artistas como Marília Mendonça e Wesley Safadão ampliaram seu alcance. Atualmente, continua ativo na música, lançando novos projetos e singles. Seu carisma e versatilidade o tornam uma figura marcante no entretenimento brasileiro.',
'4 de abril de 1991',
'Patrocínio - MG',
'2007 – Presente',
'Pra Te Fazer Lembrar – 2012 / Destino – 2013 / 11 Vidas – 2015',
'style/assets/images/fotos_cantores/universitario_solo/lucasLucco.png',
'Mozão - 2014',
'+10 milhões',
'+132 milhões'),
(default, 'Luiza Martins',
'style/assets/images/cantor_específico/universitarios_solo/luizaMartins.png',
'Luiza Martins Passos Firpe Santos é uma cantora e compositora brasileira de música sertaneja. Natural de Belo Horizonte, iniciou sua carreira em 2016 ao formar a dupla Luiza & Maurílio. A dupla ganhou destaque com músicas como “S de Saudade” e “Furando o Sinal”. Em 2021, com o falecimento de Maurílio, Luiza entrou em um período sabático. Retornou à música em 2022, iniciando sua carreira solo. Em 2023, lançou o álbum “Continua”, com músicas inéditas e regravações da antiga dupla. Seu estilo é marcado por uma voz potente e letras que exploram emoções profundas. Luiza é conhecida como a “Alcione do Sertanejo” por sua voz marcante. Além da música, é reconhecida por sua autenticidade e representatividade no cenário sertanejo. Atualmente, continua ativa na música, realizando shows e lançando novos projetos.',
'5 de novembro de 1991',
'Belo Horizonte - MG',
'2016 – Presente',
'Furando o Sinal – 2018 / S de Saudade – 2019 / Desconhecido – 2023',
'style/assets/images/fotos_cantores/universitario_solo/luizaMartins.png',
'Ponto Final (feat. Murilo Huff) - 2023',
'+21 milhões',
'+41 milhões'),
(default, 'Cantor',
'style/assets/images/cantor_específico/universitarios_solo/luizaMartins.png',
'Luan Rafael Domingos Santana nasceu em 13 de março de 1991, em Campo Grande, Mato Grosso do Sul. Desde pequeno, demonstrou talento musical, começando a cantar aos três anos. Em 2009, lançou seu álbum de estreia, "Tô de Cara", que o projetou nacionalmente com o hit "Meteoro". Com uma carreira consolidada, Luan é conhecido por sua versatilidade, transitando entre o sertanejo romântico e o pop. Ao longo dos anos, lançou diversos álbuns e DVDs de sucesso, como "Ao Vivo no Rio" e "1977". Recebeu múltiplas indicações ao Grammy Latino e é um dos artistas mais premiados do Brasil. Além da música, participou de campanhas publicitárias e programas de TV. Seu carisma e talento o tornaram um ícone da música jovem brasileira. Atualmente, continua ativo, lançando novos projetos e realizando turnês. Luan é reconhecido por sua dedicação aos fãs e por inovar constantemente em sua carreira.',
'13 de março de 1991',
'Campo Grande - MS',
'2007 – Luan Santana',
'Meteoro – 2009 / Te Esperando – 2013 / Quando a Bad Bater – 2019',
'style/assets/images/fotos_cantores/universitario_solo/luanSantana.png',
'Abalo Emocional - 2023',
'+209 milhões',
'+160 milhões'),
(default, 'Marília Mendonça',
'style/assets/images/cantor_específico/universitarios_solo/mariliaMendonca.png',
'Marília Dias Mendonça nasceu em 22 de julho de 1995, em Cristianópolis, Goiás. Iniciou sua carreira como compositora, escrevendo para diversos artistas sertanejos. Em 2016, lançou seu primeiro DVD homônimo, que a consagrou nacionalmente com o hit "Infiel". Reconhecida como a "Rainha da Sofrência", suas músicas abordavam temas de amor e empoderamento feminino. Em 2019, lançou o projeto "Todos os Cantos", gravando shows em todas as capitais brasileiras. Recebeu diversos prêmios, incluindo o Grammy Latino de Melhor Álbum de Música Sertaneja. Infelizmente, faleceu em 5 de novembro de 2021, vítima de um acidente aéreo. Mesmo após sua morte, suas músicas continuam fazendo sucesso e emocionando fãs. Marília deixou um legado importante na música brasileira, influenciando uma geração de artistas. Sua voz e autenticidade permanecem vivas nas canções que eternizou.',
'22 de julho de 1995',
'Cristianópolis - GO',
'2014 – 2021',
'Infiel – 2016 / Eu Sei de Cor – 2016 / Todo Mundo Vai Sofrer – 2019',
'style/assets/images/fotos_cantores/universitario_solo/mariliaMendonca.png',
'Leão - 2020',
'+480 milhões',
'+438 milhões'),
(default, 'Michel Teló',
'style/assets/images/cantor_específico/universitarios_solo/michelTelo.png',
'Michel Teló nasceu em 21 de janeiro de 1981, em Medianeira, Paraná. Começou sua carreira musical ainda criança, participando de bandas escolares. Ganhou notoriedade nacional como vocalista do grupo Tradição, onde permaneceu por 11 anos. Em 2009, iniciou carreira solo, alcançando sucesso mundial com o hit "Ai Se Eu Te Pego" em 2011. A música liderou paradas em diversos países e se tornou um fenômeno global. Michel é conhecido por seu carisma e habilidade com instrumentos como sanfona e violão. Além da música, participou como técnico no programa "The Voice Brasil". Lançou vários álbuns e DVDs ao longo da carreira, consolidando-se no cenário sertanejo. Recebeu prêmios e indicações importantes, incluindo o Grammy Latino. Atualmente, continua ativo, lançando novas músicas e realizando shows.',
'21 de janeiro de 1981',
'Medianeira - PR',
'1997 – Presente',
'Fugidinha – 2010 / Humilde Residência – 2011 / Amiga da Minha Irmã – 2012',
'style/assets/images/fotos_cantores/universitario_solo/michelTelo.png',
'Ai Se Eu Te Pego - 2011',
'+322 milhões',
'+1,2 bilhão'),
(default, 'Murilo Huff',
'style/assets/images/cantor_específico/universitarios_solo/muriloHuff.png',
'Murilo Huff nasceu em 14 de outubro de 1995, em Goiânia, Goiás. Iniciou sua trajetória na música como compositor, tendo canções gravadas por diversos artistas. Em 2018, lançou seu primeiro álbum, "Pra Ouvir Tomando Uma", que o destacou como cantor. Foi namorado da cantora Marília Mendonça, com quem teve um filho, Léo. Após a morte de Marília em 2021, Murilo continuou sua carreira, lançando novos projetos. É conhecido por suas letras emotivas e voz marcante no sertanejo romântico. Lançou álbuns como "Ao Vivão" e "Pra Ouvir Tomando Uma 2". Suas músicas frequentemente abordam temas de amor e superação. Murilo é considerado uma das promessas do sertanejo atual. Atualmente, segue ativo, realizando shows e compondo novas canções.',
'14 de outubro de 1995',
'Goiânia - GO',
'2018 – Presente',
'Frieza – 2020 / Desejando Eu – 2021 / Uma Ex – 2021',
'style/assets/images/fotos_cantores/universitario_solo/muriloHuff.png',
'Dois Enganados (feat. Marília Mendonça) - 2019',
'+251 milhões',
'+313 milhões'),
(default, 'Naiara Azevedo',
'style/assets/images/cantor_específico/universitarios_solo/naiaraAzevedo.png',
'Naiara de Fátima Azevedo nasceu em 30 de outubro de 1989, em Campo Mourão, Paraná. Desde jovem, demonstrou interesse pela música, cantando em corais de igreja. Formou-se em Estética e Cosmetologia, mas decidiu seguir carreira musical. Ganhou destaque com a música "50 Reais", lançada em 2016. Seu estilo mistura sertanejo com elementos de outros gêneros, abordando temas de empoderamento feminino. Participou de programas de TV e realizou shows por todo o Brasil. Lançou álbuns como "Totalmente Diferente" e "Contraste". É conhecida por sua energia no palco e letras impactantes. Naiara também participou do reality show "Big Brother Brasil" em 2022. Atualmente, continua ativa na música, lançando novos projetos.',
'30 de outubro de 1989',
'Campo Mourão - PR',
'2011 – Presente',
'50 Reais – 2016 / Ex do Seu Atual – 2017 / Pegada Que Desgrama – 2018',
'style/assets/images/fotos_cantores/universitario_solo/naiaraAzevedo.png',
'Palhaça (feat. Ana Castela) - 2023',
'+164 milhões',
'+302 milhões'),
(default, 'Paula Fernandes',
'style/assets/images/cantor_específico/universitarios_solo/paulaFernandes.png',
'Paula Fernandes de Souza nasceu em 28 de agosto de 1984, em Sete Lagoas, Minas Gerais. Começou a cantar aos oito anos e, aos dez, lançou seu primeiro álbum independente. Aos doze, mudou-se para São Paulo, onde foi contratada por uma companhia de rodeios, ganhando experiência em apresentações ao vivo. Em 2005, sua música “Ave Maria Natureza” integrou a trilha sonora da novela “América”, aumentando sua visibilidade nacional. Seu álbum “Paula Fernandes: Ao Vivo” (2011) foi um marco em sua carreira, consolidando-a como uma das principais vozes do sertanejo romântico. Paula é conhecida por sua voz doce e por mesclar sertanejo com elementos de pop e música romântica. Ao longo dos anos, lançou diversos álbuns de sucesso e realizou turnês nacionais e internacionais. Recebeu prêmios importantes, incluindo dois Grammy Latinos. Em 2023, lançou o álbum “11:11”, mostrando sua constante evolução artística. Atualmente, continua ativa na música, encantando fãs com seu talento e carisma.',
'28 de agosto de 1984',
'Sete Lagoas - MG',
'1993 – Presente',
'Pássaro de Fogo – 2009 / Pra Você – 2011 / Um Ser Amor – 2013',
'style/assets/images/fotos_cantores/universitario_solo/paulaFernandes.png',
'Não Precisa (feat. Victor & Leo) - 2010',
'+42 milhões',
'+239 milhões'),
(default, 'Yasmin Santos',
'style/assets/images/cantor_específico/universitarios_solo/yasminSantos.png',
'Yasmin dos Santos de Jesus nasceu em 10 de janeiro de 1998, em Guarujá, São Paulo. Iniciou sua carreira tocando em bares locais e ganhou notoriedade ao publicar um vídeo cantando “Amante Não Tem Lar”, de Marília Mendonça, que viralizou na internet. Em 2018, lançou seu primeiro single, “Saudade Nível Hard”, que ficou entre as 10 músicas mais tocadas nas rádios e plataformas de streaming. Assinou contrato com a Sony Music em 2019 e, no mesmo ano, gravou seu primeiro DVD, “Ao Vivo em São Paulo”, com participações de artistas renomados como Marília Mendonça e Wesley Safadão. Yasmin é conhecida por seu timbre de voz semelhante ao de Marília Mendonça e por suas músicas que abordam temas de amor e sofrência. Lançou diversos EPs e singles de sucesso, consolidando-se como uma das promessas do sertanejo atual. Em 2022, lançou o DVD “Ao Vivo em Goiânia”, expandindo ainda mais seu alcance nacional. Além de cantora, é compositora e toca instrumentos como violão e guitarra. Sua autenticidade e talento têm conquistado uma base sólida de fãs. Atualmente, segue ativa na música, lançando novos projetos e realizando shows por todo o Brasil.',
'10 de janeiro de 1998',
'Guarujá - SP',
'2018 – Presente',
'Saudade Nível Hard – 2018 / Pronta Pra Trair – 2018 / Dói Saber (feat. Hugo e Guilherme) – 2023',
'style/assets/images/fotos_cantores/universitario_solo/yasminSantos.png',
'Para, Pensa e Volta (feat. Marília Mendonça) - 2019',
'+128 milhões',
'+221 milhões');

-- Inserindo cantores universitários - duplas
insert into artistas values
(default, 
'Bruninho & Davi', 
'style/assets/images/cantor_específico/universitarios_dupla/bruninho&davi.png',
'Bruninho (Bruno Alessandro da Silva Cerri) e Davi (Davi Garcia de Ávila Filho) são naturais de Campo Grande, Mato Grosso do Sul. Amigos desde a infância, começaram na música tocando em uma banda de rock chamada Vega. Em 2009, decidiram formar a dupla sertaneja Bruninho & Davi, lançando a primeira música de trabalho, "Zona Sul". Em 2010, ganharam destaque com o clipe "Vamo Mexê", em parceria com Michel Teló. O sucesso nacional veio com "Se Namorar Fosse Bom", lançada em 2012. Assinaram contrato com a Sony Music em 2014 e lançaram o DVD "Ao Vivo em Campo Grande". A dupla é conhecida por misturar sertanejo universitário com pop e humor em suas músicas. Participaram de programas de TV e conquistaram uma base sólida de fãs. Continuam ativos, lançando novos projetos e realizando shows por todo o país. Em 2024, lançaram o álbum "Ao Vivo em Curitiba".',
'Bruninho: 3 de abril de 1989 / Davi: 17 de setembro de 1985',
'Bruninho: Campo Grande - MS / Davi: Campo Grande - MS',
'2009 - Presente',
'Se Namorar Fosse Bom – 2012 / Vamo Mexê (feat. Michel Teló) – 2010 / Imagina com as Amigas – 2014',
'style/assets/images/fotos_cantores/universitario_dupla/bruninho&davi.png',
'E Essa Boca Aí? - 2017',
'+93 milhões',
'+79 milhões'),
(default, 
'Bruno & Barretto', 
'style/assets/images/cantor_específico/universitarios_dupla/bruno&barretto.png',
'Bruno César Bortholazzi (Bruno) e André Luiz Evaristo Bonini Tavares (Barretto) formam a dupla Bruno & Barretto, originária do Paraná. Se conheceram em 2010 na cidade de Londrina e decidiram formar a dupla sertaneja. Ganhando notoriedade com vídeos na internet, chamaram a atenção de empresários do ramo musical. Em 2015, lançaram o álbum de estreia "Farra, Pinga e Foguete", que os projetou nacionalmente. Participaram de programas de TV e conquistaram fãs com seu estilo irreverente e animado. A dupla é conhecida por mesclar sertanejo tradicional com influências do sertanejo universitário. Continuam ativos, lançando novas músicas e realizando shows por todo o Brasil. Em 2023, lançaram o álbum "Blessed", com destaque para a faixa "Bruno & Barretto - Blessed - Episódio 8 (EPK / Tour USA)". São reconhecidos por sua energia contagiante e carisma no palco. A dupla mantém uma forte presença nas redes sociais e plataformas de streaming.',
'Bruno: 7 de maio de 1992 / Barretto: 23 de novembro de 1989',
'Bruno: Sertanópolis - PR / Barretto: Alvorada do Sul - PR',
'2014 - Presente',
'Eu Quero é Rolo – 2016 / Cópia Mal Feita – 2017 / Bruno & Barretto - Blessed - Episódio 8 (EPK / Tour USA) – 2023',
'style/assets/images/fotos_cantores/universitario_dupla/bruno&barretto.png',
'Farra, Pinga e Foguete - 2015',
'+90 milhões',
'+165 milhões'),
(default, 
'Clayton & Romário', 
'style/assets/images/cantor_específico/universitarios_dupla/clayton&romario.png',
'Clayton e Romário são irmãos naturais de Goiânia, Goiás, que começaram a cantar ainda na infância. Inicialmente, se apresentavam em barzinhos e churrascarias, ganhando experiência e visibilidade. Moraram por um período na Espanha e, ao retornarem ao Brasil, estabeleceram-se em Belo Horizonte, Minas Gerais. A carreira da dupla ganhou força na capital mineira, onde conquistaram uma base sólida de fãs. Em 2020, lançaram o álbum "No Churrasco 2", que consolidou seu estilo descontraído e animado. São conhecidos por suas letras bem-humoradas e por mesclar sertanejo com outros ritmos. A dupla mantém uma forte presença nas redes sociais e plataformas de streaming. Continuam ativos, lançando novos projetos e realizando shows por todo o Brasil. Em 2023, lançaram a música "Pingaiada", que se tornou um dos seus maiores sucessos. Clayton & Romário são considerados uma das duplas mais promissoras do sertanejo atual.',
'Clayton: 13 de dezembro de 1985 / Romário: 19 de junho de 1990',
'Clayton: Goiânia - GO / Romário: Goiânia - GO',
'2010 - Presente',
'Nosso Amor é Lindo – 2020 / Água nos Zói – 2021 / Pingaiada – 2023',
'style/assets/images/fotos_cantores/universitario_dupla/clayton&romario.png',
'Namorando ou Não (feat. Luan Santana) - 2023',
'+174 milhões',
'+162 milhões'),
(default, 
'Cleber & Cauan', 
'style/assets/images/cantor_específico/universitarios_dupla/cleber&cauan.png',
'Cleber e Cauan são amigos de infância naturais de Ceres, interior de Goiás. Cleber começou a cantar aos 8 anos e participou de outras duplas antes de formar a atual. A dupla foi formada em 2010 e começou se apresentando em bares do Distrito Federal e entorno. Em 2013, alcançaram sucesso nacional com a música "Mel Nesse Trem". O hit "Solteiro Desapegado", com participação de Wesley Safadão, aumentou ainda mais sua notoriedade. Em 2017, lançaram o álbum "Resenha", seguido por "Resenha 2 (Ao Vivo)" em 2018. A dupla é conhecida por suas músicas animadas e letras que falam sobre relacionamentos e festas. Receberam diversas certificações da Pro-Música Brasil. Continuam ativos, lançando novos projetos e realizando shows por todo o país. Cleber & Cauan são considerados uma das duplas mais populares do sertanejo atual.',
'Cleber: N/A / Cauan: N/A',
'Cleber: Ceres - GO / Cauan: Ceres - GO',
'2010 - Presente',
'Mel Nesse Trem – 2013 / Só Que Não – 2014 / Solteiro Desapegado (feat. Wesley Safadão) – 2015',
'style/assets/images/fotos_cantores/universitario_dupla/cleber&cauan.png',
'Quase - 2017',
'+85 milhões',
'+105 milhões'),
(default, 
'Diego & Victor Hugo', 
'style/assets/images/cantor_específico/universitarios_dupla/diego&victorHugo.png',
'Diego Felix Pereira (Brasília, 10 de julho de 1984) e Elias Anderson de Souza (Uberlândia, 17 de dezembro de 1988), formam a dupla Diego & Victor Hugo. Antes de se unirem, atuavam como compositores, escrevendo músicas para artistas como Henrique & Juliano e Wesley Safadão. A união da dupla marcou o início de uma carreira de sucesso no cenário sertanejo. Em 2017, lançaram a música "O Alvo", em parceria com Henrique & Juliano, que ficou estourada nas rádios. Em 2018, lançaram "Infarto", uma das músicas mais ouvidas nas rádios naquele ano. Victor Hugo é autor da música "Largado às Traças", sucesso da dupla Zé Neto & Cristiano. A dupla é conhecida por suas letras românticas e melodias envolventes. Continuam ativos, lançando novos projetos e realizando shows por todo o Brasil. Em 2023, lançaram a música "Sem Contra Indicação", com participação especial de Bruno & Marrone.',
'Diego: 10 de julho de 1984 / Victor Hugo: 17 de dezembro de 1988',
'Diego: Brasília - DF / Victor Hugo: Uberlândia - MG',
'2014 - Presente',
'O Alvo (feat. Henrique & Juliano) – 2017 / Infarto – 2018 / Sem Contra Indicação (feat. Bruno & Marrone) – 2023',
'style/assets/images/fotos_cantores/universitario_dupla/diego&victorHugo.png',
'Facas (feat. Bruno & Marrone) - 2020',
'+292 milhões',
'+569 milhões'),
(default, 
'Fernando & Sorocaba', 
'style/assets/images/cantor_específico/universitarios_dupla/fernando&sorocaba.png',
'Fernando Zorzanello Bonifácio (Ji-Paraná, 21 de abril de 1984) e Fernando Fakri de Assis, conhecido como Sorocaba (São Paulo, 15 de setembro de 1980), formam a dupla Fernando & Sorocaba. A dupla foi criada em 2006 e começou a tocar em bares e boates em Londrina e região. Com o sucesso instantâneo, nasceu a dupla Fernando & Sorocaba. A partir de 2014, transferiram sua carreira para sua gravadora independente, a FS Produções Artísticas. Criaram um show beneficente e a fundação "FS Premium" para causas sociais. Fernando é também produtor musical e já trabalhou com artistas como Chitãozinho & Xororó, Marcos & Belutti e Luan Santana. Sorocaba é conhecido por seu trabalho como compositor e empresário no meio sertanejo. A dupla é reconhecida por suas apresentações inovadoras e uso de tecnologia nos shows. Continuam ativos, lançando novos projetos e realizando shows por todo o Brasil.',
'Fernando: 21 de abril de 1984 / Sorocaba: 15 de setembro de 1980',
'Fernando: Ji-Paraná - RO / Sorocaba: São Paulo - SP',
'2006 - Presente',
'Madri – 2009 / Paga Pau – 2010 / As Mina Pira – 2011',
'style/assets/images/fotos_cantores/universitario_dupla/fernando&sorocaba.png',
'Bom Rapaz (feat. Jorge & Mateus) - 2017',
'+96 milhões',
'+227 milhões'),
(default, 
'Fred & Fabrício', 
'style/assets/images/cantor_específico/universitarios_dupla/fred&fabricio.png',
'Fred Liel e Fabrício Fiori formam a dupla Fred & Fabrício, oficializada em 2021. Antes de se unirem, Fred fez parte da primeira formação da dupla Fred & Gustavo, enquanto Fabrício era da dupla Geovany Reis e Fabrício. A formação da dupla surgiu de forma inesperada durante um show em que precisaram cantar juntos. Em 2021, lançaram o projeto "Acústico de Primeira", regravando sucessos da música sertaneja. Assinaram com a Som Livre e lançaram, em 2022, o DVD "Ao Quadrado", com participações especiais. Em 2023, gravaram o DVD "Infinito Pra Sempre", com faixas inéditas e regravações. A dupla é conhecida por alternar entre primeira e segunda voz nas músicas, o que chamou atenção do público. Continuam ativos, lançando novos projetos e realizando shows por todo o Brasil. Em 2024, lançaram a música "Gotejou no Celular", que ficou no Top 100 do Spotify Brasil.',
'Fred: 16 de abril de 1988 / Fabrício: 21 de julho de 1993',
'Fred: Itumbiara - GO / Fabrício: São Sebastião do Paraíso - MG',
'2021 - Presente',
'Proposta Alcoolizada – 2021 / Paredão Desmoronou (feat. Hugo & Guilherme) – 2022 / Gotejou no Celular (feat. Clayton & Romário) – 2024',
'style/assets/images/fotos_cantores/universitario_dupla/fred&fabricio.png',
'Guarda Roupa (feat. Hugo & Guilherme) - 2023',
'+49 milhões',
'+26 milhões'),
(default, 
'George Henrique & Rodrigo', 
'style/assets/images/cantor_específico/universitarios_dupla/georgeHenrique&rodrigo.png',
'George Henrique e Rodrigo são irmãos naturais de Goiânia, Goiás. A dupla foi formada após George Henrique perceber o talento vocal de Rodrigo durante cantorias familiares. Iniciaram a carreira em bares locais, com Rodrigo assumindo a primeira voz. Em 2011, lançaram "Receita de Amar", que chamou a atenção de Bruno, da dupla Bruno & Marrone, tornando-se seu mentor. Em 2013, lançaram o álbum "Conto Até Dez", com várias composições próprias. O álbum "Ouça com o Coração" (2016) contou com participações de Jorge & Mateus e Henrique & Juliano. Em 2017, assinaram com a Universal Music Brasil e lançaram "De Copo em Copo", produzido por Eduardo Pepato. Em 2019, lançaram o EP "Bagunça Minha Vida", produzido por Ivan Miyazato. O EP "Ao Vivo em Brasília" (2022) destacou-se com a música "Vai Lá em Casa Hoje", em parceria com Marília Mendonça, tornando-se um dos maiores sucessos da dupla. Em 2023, lançaram o álbum "Influências", com regravações de clássicos sertanejos, e o single "Beijo Equivocado", em parceria com Guilherme & Benuto.',
'George Henrique: 3 de novembro de 1986 / Rodrigo: 1989',
'George Henrique: Goiânia - GO / Rodrigo: Goiânia - GO',
'2011 - Presente',
'Receita de Amar – 2011 / Beijo Equivocado (feat. Guilherme & Benuto) – 2023 / Resquícios – 2024',
'style/assets/images/fotos_cantores/universitario_dupla/georgeHenrique&rodrigo.png',
'Vai Lá Em Casa Hoje (feat. Marília Mendonça) - 2021',
'+346 milhões',
'+321 milhões'),
(default, 
'Guilherme & Benuto', 
'style/assets/images/cantor_específico/universitarios_dupla/guilherme&benuto.png',
'Guilherme Antônio Artioli e Haroldo Bevenuto Machado Artioli, conhecidos como Guilherme & Benuto, são irmãos nascidos em Campinas, São Paulo. Desde cedo, demonstraram talento musical, com Gui aprendendo sanfona aos nove anos e Nuto, formado em música erudita, tocando violino desde os 11. Iniciaram a carreira tocando chorinho, forró e samba em bares locais. Antes de formarem a dupla, integraram o trio Villa Baggage por uma década. Destacaram-se como compositores, escrevendo para artistas como Jorge & Mateus e Zé Neto & Cristiano. Em 2020, lançaram o álbum "Amando, Bebendo e Sofrendo", seguido por "DRIVE-IN" em 2021. Em 2024, lançaram "Deu Rolo de Novo", celebrando mais de 13 milhões de ouvintes no Spotify. Atualmente, trabalham no projeto "In Casa", gravado em Ribeirão Preto.',
'Guilherme: 13 de junho de 1990 / Benuto: 19 de novembro de 1988',
'Guilherme: Campinas - SP / Benuto: Campinas - SP',
'2019 - Presente',
'3 Batidas – 2019 / Pulei na Piscina – 2021 / Duas Três (feat. Ana Castela e Adriano Rhod) – 2023',
'style/assets/images/fotos_cantores/universitario_dupla/guilherme&benuto.png',
'Haja Colírio (feat. Hugo & Guilherme) - 2022',
'+317 milhões',
'+353 milhões'),
(default, 
'Guilherme & Santiago', 
'style/assets/images/cantor_específico/universitarios_dupla/guilherme&santiago.png',
'Guilherme (Herickson Cardoso Rosa) e Santiago (Henzzo Cardoso Rosa) são irmãos naturais de Goiânia, Goiás. Guilherme iniciou a carreira musical nos Estados Unidos, retornando ao Brasil no início dos anos 90. Durante as férias, gravaram um jingle para um candidato a prefeito, que fez sucesso local. Decidiram formar a dupla e começaram a se apresentar em eventos políticos e bares. Trabalharam na feira hippie de Goiânia para financiar o primeiro disco. A primeira apresentação ao vivo foi na abertura de um show de Chrystian & Ralf. Ao longo dos anos, consolidaram-se como uma das principais duplas sertanejas do Brasil. Em 2017, Guilherme participou do programa "Dancing Brasil", exibido pela RecordTV. Em 2018, participou do programa "Bancando o Chef", também na RecordTV.',
'Guilherme: 15 de outubro de 1969 / Santiago: 22 de março de 1976',
'Guilherme: Goiânia - GO / Santiago: Goiânia - GO',
'1994 - Presente',
'E Daí? – 2009 / Tá Se Achando – 2010 / Quando Bebe – 2012',
'style/assets/images/fotos_cantores/universitario_dupla/guilherme&santiago.png',
'Meia Noite e Meia - 1994',
'+92 milhões',
'+39 milhões'),
(default, 
'Henrique & Diego', 
'style/assets/images/cantor_específico/universitarios_dupla/henrique&diego.png',
'Henrique (Luiz Henrique Teixeira) e Diego (Diego Barros da Silva) são naturais de Cuiabá, Mato Grosso. Formaram a dupla em 2005, iniciando a carreira musical na região Centro-Oeste. Em 2010, lançaram o álbum "Top do Verão", com destaque para a faixa homônima. O sucesso nacional veio com "Festa Boa" (2013), em parceria com Gusttavo Lima. Em 2015, "Suíte 14", com MC Guimê, alcançou o topo das paradas brasileiras. Outros sucessos incluem "Senha do Celular" e "Raspão", com Simone & Simaria. Em 2017, lançaram o álbum "De Braços Abertos - Ao Vivo no Rio de Janeiro". Continuam ativos, lançando novos projetos e realizando shows por todo o Brasil.',
'Henrique: 2 de junho de 1984 / Diego: 19 de junho de 1986',
'Henrique: Cuiabá - MT / Diego: Cuiabá - MT',
'2005 - Presente',
'Festa Boa (feat. Gusttavo Lima) – 2013 / Senha do Celular – 2015 / Raspão (feat. Simone & Simaria) – 2017',
'style/assets/images/fotos_cantores/universitario_dupla/henrique&diego.png',
'Suíte 14 (feat. MC Guimê) - 2015',
'+135 milhões',
'+278 milhões'),
(default, 
'Henrique & Juliano', 
'style/assets/images/cantor_específico/universitarios_dupla/henrique&juliano.png',
'Henrique & Juliano são irmãos naturais de Palmeirópolis, Tocantins. Formaram a dupla em 2011 e rapidamente conquistaram o cenário sertanejo brasileiro. Com vozes marcantes e letras que falam de amor e cotidiano, tornaram-se referência no gênero. Lançaram diversos álbuns ao vivo, como "Ao Vivo em Palmas" (2013) e "Ao Vivo em Brasília" (2014). Em 2015, ganharam o Prêmio Multishow na categoria Melhor Show. Em 2021, lançaram o álbum "Manifesto Musical", consolidando ainda mais sua carreira. Em 2023, lançaram "To Be Ao Vivo Em Brasília" e "To Be". São conhecidos por arrastar multidões em seus shows, com média de público de 35 mil pessoas por apresentação. Atualmente, são considerados os artistas mais populares do Brasil, segundo a Billboard Artistas 25. Continuam ativos, lançando novos projetos e realizando turnês por todo o país.',
'Henrique: 23 de maio de 1989 / Juliano: 27 de novembro de 1990',
'Henrique: Palmeirópolis - TO / Juliano: Palmeirópolis - TO',
'2011 - Presente',
'Cuida Bem Dela – 2014 / Até Você Voltar – 2014 / Flor e o Beija-Flor (feat. Marília Mendonça) – 2015',
'style/assets/images/fotos_cantores/universitario_dupla/henrique&juliano.png',
'Liberdade Provisória - 2019',
'+414 milhões',
'+561 milhões'),
(default, 
'Hugo & Guilherme', 
'style/assets/images/cantor_específico/universitarios_dupla/hugo&guilherme.png',
'Hugo (Spártaco Luiz Neves Vezzani) e Guilherme (Matheus Neves) são naturais de Morrinhos e Goiânia, respectivamente. Formaram a dupla em 2015 após se conhecerem em uma casa de shows em Goiânia. Hugo já havia trilhado carreira solo, enquanto Guilherme cursava agronomia. Contaram com o apoio de Henrique & Juliano para iniciar a carreira. Lançaram o álbum de estreia "Acústico e Ao Vivo" em 2016. Emplacaram sucessos como "Coração na Cama" e "Namorada Reserva". A música "Mal Feito", com participação de Marília Mendonça, foi um dos maiores hits da dupla. Em 2023, lançaram o álbum "Original", seguido por "062" em 2024. São conhecidos por mesclar o sertanejo tradicional com elementos modernos. Continuam ativos, realizando shows e lançando novos projetos.',
'Hugo: 4 de março de 1991 / Guilherme: 4 de dezembro de 1994',
'Hugo: Morrinhos - GO / Guilherme: Goiânia - GO',
'2015 - Presente',
'Coração na Cama – 2017 / Namorada Reserva – 2018 / Metade de Mim – 2023',
'style/assets/images/fotos_cantores/universitario_dupla/hugo&guilherme.png',
'Mal Feito (feat. Marília Mendonça) - 2022',
'+366 milhões',
'+355 milhões'),
(default, 
'Ícaro & Gilmar', 
'style/assets/images/cantor_específico/universitarios_dupla/icaro&gilmar.png',
'Ícaro da Silva Mantovani e Gilmar Rodrigues de Castro são naturais de Periquito, Minas Gerais. Formaram a dupla em 2009 após o fim de uma banda de pop rock que integravam. Iniciaram a carreira tocando em bares e festas locais. Em 2017, mudaram-se para Goiânia em busca de novas oportunidades. Em 2019, ingressaram na NA Produções Artísticas, escritório da cantora Naiara Azevedo. Lançaram o álbum "Na Bebida e Na Sofrência" em 2018, com destaque para a música "Despedida". O projeto "Sextou BB", iniciado em 2019, trouxe regravações de clássicos sertanejos. Em 2022, lançaram "Ao Vivo em Campo Grande", com os hits "Imperfeitos" e "Não Me Esquecerás". Em 2023, lançaram o álbum "Nunca Deixe de Sonhar", com participações de Hugo & Guilherme e Eduardo Costa. Continuam ativos, lançando novos projetos e realizando shows por todo o Brasil.',
'Ícaro: 27 de maio de 1991 / Gilmar: 4 de dezembro de 1990',
'Ícaro: Periquito - MG / Gilmar: Periquito - MG',
'2009 - Presente',
'Despedida – 2018 / M de Mulher – 2020 / Imperfeitos – 2022',
'style/assets/images/fotos_cantores/universitario_dupla/icaro&gilmar.png',
'A Viola e Eu (feat. Eduardo Costa) - 2023',
'+32 milhões',
'+55 milhões'),
(default, 
'Israel & Rodolffo', 
'style/assets/images/cantor_específico/universitarios_dupla/israel&rodolffo.png',
'Israel Antônio Ribeiro e Rodolffo Matthaus da Silva Rios são naturais de Goianésia e Uruaçu, Goiás, respectivamente. Formaram a dupla em 1999, incentivados por seus pais. Gravaram um CD demo ainda crianças e começaram a se apresentar em comícios e festas locais. Em 2011, lançaram o álbum "Do Jeito Que Eu Queria", com destaque para as músicas "Largadão" e "Louco Desejo". Em 2012, lançaram o álbum "Marca Evidente", com participações de Jorge & Mateus e Gusttavo Lima. A música "Batom de Cereja", lançada em 2021, tornou-se um dos maiores sucessos da dupla. Participaram de diversos programas de televisão, aumentando sua visibilidade nacional. Em 2022, participaram do álbum de Paula Fernandes com a música "Tá Tudo Bem". São conhecidos por suas composições autorais e por mesclar o sertanejo tradicional com o moderno. Continuam ativos, lançando novos projetos e realizando turnês por todo o país. ',
'Israel: 23 de dezembro de 1988 / Rodolffo: 24 de agosto de 1988',
'Israel: Goianésia - GO / Rodolffo: Uruaçu - GO',
'1999 - Presente',
'Marca Evidente – 2012 / Batom de Cereja – 2021 / Tá Tudo Bem (feat. Paula Fernandes) – 2022',
'style/assets/images/fotos_cantores/universitario_dupla/israel&rodolffo.png',
'Bombonzinho (feat. Ana Castela) - 2022',
'+369 milhões',
'+217 milhões'),
(default, 
'Jads & Jadson', 
'style/assets/images/cantor_específico/universitarios_dupla/jads&jadson.png',
'Jads & Jadson são irmãos naturais de Catanduvas, Paraná. Iniciaram a carreira musical ainda jovens, participando de festivais em Ponta Porã, Mato Grosso do Sul. Gravaram o primeiro CD em 1990 e, em 2003, lançaram o álbum "Acústico", com composições próprias. O sucesso nacional veio com a música "Com Todos Menos Comigo", do álbum "Dom Brasileiro" (2004). Em 2012, lançaram "Pra Acabar Com Tudo", com destaque para a faixa-título. O DVD "É Divino - Ao Vivo em Campo Grande" (2014) consolidou a dupla no cenário sertanejo. Em 2015, lançaram o álbum "Diamante Bruto", com o single "Noite Fracassada". A dupla é conhecida por seu estilo "bruto" e influências da música caipira. Continuam ativos, realizando shows e lançando novos projetos.',
'Jads: 23 de janeiro de 1974 / Jadson: 8 de fevereiro de 1978',
'Jads: Catanduvas - PR / Jadson: Catanduvas - PR',
'1990 - Presente',
'Com Todos Menos Comigo – 2004 / Noite Fracassada – 2015 / Ressentimento – 2014',
'style/assets/images/fotos_cantores/universitario_dupla/jads&jadson.png',
'Jeito Carinhoso - 2013',
'+61 milhões',
'+89 milhões'),
(default, 
'João Bosco & Vinícius', 
'style/assets/images/cantor_específico/universitarios_dupla/joaoBosco&vinicius.png',
'João Bosco & Vinícius são amigos de infância que se conheceram em Coxim, Mato Grosso do Sul. Formaram a dupla em 1994 e são considerados pioneiros do sertanejo universitário. O primeiro álbum, "Acústico no Bar", foi lançado em 2003. O sucesso nacional veio com o hit "Chora, Me Liga", do álbum "Curtição" (2009). Receberam o Grammy Latino de Melhor Álbum de Música Sertaneja em 2011. Lançaram diversos álbuns ao longo da carreira, incluindo "A Festa" (2012) e "Ao Vivo em Goiânia" (2020). A dupla é conhecida por suas letras românticas e melodias cativantes. Continuam ativos, realizando shows e lançando novos projetos.',
'João Bosco: 11 de setembro de 1981 / Vinícius: 31 de dezembro de 1980',
'João Bosco: Rondonópolis - MT / Vinícius:  Naviraí - MS',
'1994 - Presente',
'Sorte É Ter Você – 2010 / Coração Apaixonou – 2010 / Amiga Linda – 2012',
'style/assets/images/fotos_cantores/universitario_dupla/joaoBosco&vinicius.png',
'Chora, Me Liga - 2008',
'+80 milhões',
'+38 milhões'),
(default, 
'João Lucas & Marcelo', 
'style/assets/images/cantor_específico/universitarios_dupla/joaoLucas&marcelo.png',
'João Lucas & Marcelo formaram a dupla em 2010, conquistando rapidamente o cenário sertanejo. O sucesso veio com o hit "Eu Quero Tchu, Eu Quero Tcha" (2012), que alcançou destaque nacional. Lançaram outros sucessos como "Louca Louquinha" e "Agora É Pra Valer", com participações de MC K9 e Wesley Safadão. Em 2013, lançaram o DVD "A Vida É Uma Festa! (Ao Vivo)". A dupla se destacou por mesclar sertanejo com elementos de funk e música eletrônica. Em 2019, após divergências financeiras, a dupla se separou. Marcelo Martins seguiu carreira solo, enquanto João Lucas tentou carreira política. Apesar da separação, suas músicas continuam populares nas plataformas digitais.',
'João Lucas: 5 de janeiro de 1981 / Marcelo: 3 de julho de 1985',
'João Lucas: Miranorte - TO / Marcelo: Cáceres - MT',
'2010 - 2019',
'Louca Louquinha – 2012 / Joga o Copo Pro Alto – 2014 / Agora É Pra Valer – 2015',
'style/assets/images/fotos_cantores/universitario_dupla/joaoLucas&marcelo.png',
'Eu Quero Tchu Eu Quero Tcha - 2012',
'+24 milhões',
'+34 milhões'),
(default, 
'João Neto & Frederico', 
'style/assets/images/cantor_específico/universitarios_dupla/joaoNeto&frederico.png',
'João Neto & Frederico são irmãos naturais de Goiânia, Goiás. Iniciaram a carreira musical ainda crianças, participando de eventos em feiras e pecuárias. Gravaram o primeiro CD em 2004, mas o sucesso nacional veio com o hit "Pega Fogo Cabaré" (2007). A dupla é conhecida por suas letras animadas e estilo sertanejo universitário. Lançaram diversos álbuns, incluindo "Ao Vivo" (2007) e "Ao Vivo em Goiânia" (2010). Em 2012, participaram da novela "Cheias de Charme", da Rede Globo. Continuam ativos, realizando shows e lançando novos projetos.',
'João Neto: 12 de agosto de 1979 / Frederico: 11 de março de 1982',
'João Neto: Goiânia - GO / Frederico: Goiânia - GO',
'2004 - Presente',
'Pega Fogo Cabaré – 2007 / Lê Lê Lê – 2012 / Rapariga Não – 2015',
'style/assets/images/fotos_cantores/universitario_dupla/joaoNeto&frederico.png',
'Cê Acredita (feat. MC Kevinho) - 2017',
'+83 milhões',
'+148 milhões'),
(default, 
'Jorge & Mateus', 
'style/assets/images/cantor_específico/universitarios_dupla/jorge&mateus.png',
'Naturais de Itumbiara (GO), Jorge & Mateus são uma das maiores duplas sertanejas do Brasil. Começaram cantando em bares da cidade até se destacarem nacionalmente. Lançaram o primeiro CD e DVD em 2007, chamado "Ao Vivo em Goiânia". A partir daí, estouraram com músicas românticas e animadas, se tornando referência no sertanejo universitário. A dupla é conhecida por manter uma agenda lotada, inclusive com turnês internacionais. Sempre inovaram no mercado, sendo uma das primeiras duplas a apostar fortemente em plataformas digitais. Suas músicas falam de amor, saudade e relacionamentos. Continuam sendo uma das maiores potências do sertanejo. Influenciam uma geração de novos artistas.',
'Jorge: 27 de agosto de 1982 / Mateus: 15 de julho de 1984',
'Jorge: Itumbiara - GO / Mateus: Itumbiara - GO',
'2005 - Presente',
'Pode Chorar – 2007 / Amo Noite e Dia – 2010 / Sosseguei – 2015',
'style/assets/images/fotos_cantores/universitario_dupla/jorge&mateus.png',
'Propaganda - 2018',
'+289 milhões',
'+511 milhões'),
(default, 
'Júlia & Rafaela', 
'style/assets/images/cantor_específico/universitarios_dupla/julia&rafaela.png',
'As gêmeas Júlia & Rafaela nasceram em Campo Grande (MS) e começaram a cantar ainda crianças. Filhas de músico, foram incentivadas desde cedo e viralizaram nas redes sociais cantando covers. Em 2016, lançaram o primeiro DVD "Ao Vivo em São Paulo", com participação de grandes artistas. Se destacaram no sertanejo feminino com músicas que falam de amor, empoderamento e sofrência. São conhecidas pela harmonia vocal perfeita, típica de irmãos gêmeos. Ao longo da carreira, amadureceram o estilo, transitando do sertanejo mais adolescente para músicas mais maduras e românticas. Mantêm uma presença forte nas plataformas digitais. Continuam ativas com novos projetos e parcerias.',
'04 de maio de 2000',
'Campo Grande - MS',
'2015 - Presente',
'10% - Versão Feminina – 2016 / Traiu Porque Quis – 2019 / Disfarce – 2020',
'style/assets/images/fotos_cantores/universitario_dupla/julia&rafaela.png',
'Besteira Feita (feat. Hugo & Guilherme) - 2023',
'+36 milhões',
'+11 milhões'),
(default, 
'Júnior & Cezar', 
'style/assets/images/cantor_específico/universitarios_dupla/junior&cezar.png',
'Naturais de Santa Helena (PR), Júnior & Cezar começaram cantando em bares e festas da região. Ficaram conhecidos pelo timbre forte e letras que valorizam o sertanejo bruto. O reconhecimento nacional veio após o lançamento da música "Das Duas Uma", em parceria com Bruno & Marrone. Desde então, se destacaram como representantes do sertanejo mais raiz e modão na nova geração. Gravaram o DVD "Só Modão" que reforçou essa identidade. A dupla aposta na mistura de romantismo e sofrência com arranjos tradicionais. Sempre fazem parcerias com artistas grandes do segmento. Continuam ativos, lançando singles e participando de festivais sertanejos pelo Brasil.',
'Júnior: 24 de setembro de 1989 / Cezar: 20 de março de 1991',
'Júnior: Santa Helena - PR / Cezar: Santa Helena - PR',
'2013 - Presente',
'Das Duas Uma – 2019 / Dois Fugitivos – 2020 / 4M – 2021',
'style/assets/images/fotos_cantores/universitario_dupla/junior&cezar.png',
'Clone - 2020',
'+95 milhões',
'+33 milhões'),
(default, 
'Maiara & Maraisa', 
'style/assets/images/cantor_específico/universitarios_dupla/maiara&maraisa.png',
'As gêmeas Maiara & Maraisa são de São José dos Quatro Marcos (MT) e cantam juntas desde a infância. A carreira começou profissionalmente em 2013, mas o sucesso veio em 2015 com o DVD "Ao Vivo em Goiânia", que trouxe hits como "10%". Elas são conhecidas por dar voz ao empoderamento feminino dentro do sertanejo, especialmente na vertente da sofrência. Além da carreira própria, já compuseram para grandes nomes, como Jorge & Mateus e Henrique & Juliano. Foram grandes amigas e parceiras musicais de Marília Mendonça, com quem gravaram vários projetos. Suas letras falam de amor, superação, bebidas e liberdade feminina. São atualmente uma das maiores duplas femininas do Brasil.',
'31 de dezembro de 1987',
'São José dos Quatro Marcos - MT',
'2013 - Presente',
'10% – 2015 / A Culpa É Nossa – 2020 / Presepada (feat. Marília Mendonça) – 2022',
'style/assets/images/fotos_cantores/universitario_dupla/maiara&maraisa.png',
'Medo Bobo - 2016',
'+199 milhões',
'+696 milhões'),
(default, 
'Marcos & Belutti', 
'style/assets/images/cantor_específico/universitarios_dupla/marcos&belutti.png',
'A dupla é formada por Leonardo Prado de Souza (Marcos) e Bruno Belucci Pereira (Belutti), naturais de São Paulo. Se conheceram em 2007 através de amigos em comum e, rapidamente, perceberam a química musical. No mesmo ano lançaram seu primeiro DVD “Ao Vivo”, que os colocou no cenário nacional. Misturam sertanejo romântico com baladas animadas e já fizeram parcerias com artistas de vários estilos. O sucesso veio com músicas como “Domingo de Manhã”, que ficou meses nas paradas. São conhecidos pela potência vocal e pelo carisma no palco. Gravaram projetos internacionais, como em Punta del Este e em São Paulo com pegada mais intimista. A dupla segue ativa, sempre inovando no sertanejo.',
'Marcos: 21 de agosto de 1983 / Belutti: 07 de novembro de 1981',
'Marcos: São Paulo - SP / Belutti: São Paulo - SP',
'2007 - Presente',
'Domingo de Manhã – 2014 / Eu Era – 2017 / Romântico Anônimo – 2020',
'style/assets/images/fotos_cantores/universitario_dupla/marcos&belutti.png',
'Aquele 1% (feat. Wesley Safadão) - 2015',
'+97 milhões',
'+278 milhões'),
(default, 
'Matheus & Kauan', 
'style/assets/images/cantor_específico/universitarios_dupla/matheus&kauan.png',
'Irmãos de Itapuranga (GO), Matheus & Kauan começaram a carreira no início dos anos 2010. Matheus já era compositor de sucesso, com músicas gravadas por Luan Santana, Jorge & Mateus, Michel Teló e outros. A dupla começou oficialmente em 2010, com um som moderno e letras românticas. Ganharam grande espaço no sertanejo universitário e no pop sertanejo, com hits que viralizaram. Músicas como “Que Sorte a Nossa” e “O Nosso Santo Bateu” os consolidaram nas paradas. Sempre presentes nas plataformas digitais, acumulam bilhões de streams. Seus projetos costumam ter grande repercussão, como os DVDs "Na Praia". Atualmente são referência na nova geração do sertanejo.',
'Matheus: 04 de outubro de 1990 / Kauan: 07 de dezembro de 1988',
'Matheus: Itapuranga - GO / Kauan: Itapuranga - GO',
'2010 - Presente',
'Que Sorte a Nossa – 2015 / O Nosso Santo Bateu" – 2016 / Te Assumi Pro Brasil – 2017',
'style/assets/images/fotos_cantores/universitario_dupla/matheus&kauan.png',
'Vou Ter Que Superar (feat. Marília Mendonça) - 2019',
'+283 milhões',
'+746 milhões'),
(default, 
'Munhoz & Mariano', 
'style/assets/images/cantor_específico/universitarios_dupla/munhoz&mariano.png',
'Naturais de Campo Grande (MS), Munhoz (Rafael Calux) e Mariano (Ricardo Mariano) se conheceram na faculdade. Começaram a cantar juntos em 2006 e conquistaram o Brasil com o hit “Camaro Amarelo”. O primeiro grande sucesso veio em 2010 com o DVD “Ao Vivo em Campo Grande”. São conhecidos pelo estilo descontraído e por misturar sertanejo com pegada universitária e balada. Suas letras geralmente trazem humor, festas e relacionamentos. Apesar de terem diminuído o ritmo nos últimos anos, continuam ativos e lançando projetos. A dupla foi uma das pioneiras em viralizar músicas através de coreografias e redes sociais. Mantêm uma base de fãs fiel por todo o país.',
'Munhoz: 24 de abril de 1986 / Mariano: 15 de outubro de 1986',
'Munhoz: Campo Grande - MS / Mariano: Campo Grande - MS',
'2006 - Presente',
'Camaro Amarelo – 2012 / Vou Pegar Você e Tãe – 2012 / Copo na Mão – 2015',
'style/assets/images/fotos_cantores/universitario_dupla/munhoz&mariano.png',
'Balada Louca (feat. João Neto & Frederico) - 2012',
'+29 milhões',
'+61 milhões'),
(default, 
'Simone & Simaria', 
'style/assets/images/cantor_específico/universitarios_dupla/simone&simaria.png',
'Naturais de Uibaí, Bahia, Simone e Simaria começaram como backing vocals de Frank Aguiar. A carreira como dupla começou em 2012, quando lançaram o álbum "As Coleguinhas - Vol. 1". Elas conquistaram o país misturando sertanejo, forró e sofrência, com letras sobre amor, empoderamento e superação. O sucesso veio com hits como “Meu Violão e o Nosso Cachorro” e “Loka” (feat. Anitta). Conhecidas pelo carisma e pela autenticidade, as irmãs sempre foram muito queridas pelo público. Em 2022, anunciaram uma pausa na carreira como dupla para seguir projetos individuais. Mesmo assim, o legado delas segue muito forte no sertanejo.',
'Simone: 24 de maio de 1984 / Simaria: 16 de junho de 1982',
'Simone: Uibaí - BA / Simaria: Uibaí - BA',
'2012 - 2022',
'Meu Violão e o Nosso Cachorro – 2015 / Loka (feat. Anitta) – 2017 / Regime Fechado – 2017',
'style/assets/images/fotos_cantores/universitario_dupla/simone&simaria.png',
'Foi Pá Pum - 2020',
'+164 milhões',
'+357 milhões'),
(default, 
'Thaeme & Thiago', 
'style/assets/images/cantor_específico/universitarios_dupla/thaeme&thiago.png',
'A dupla surgiu em 2011, formada por Thaeme Mariôto (vencedora do programa Ídolos, em 2007) e José Lazaro Servo, o Thiago. Misturam sertanejo romântico com pegada universitária. O apadrinhamento de Sorocaba (da dupla Fernando & Sorocaba) impulsionou a carreira logo de início. Ganharam projeção nacional com hits como “Ai Que Dó”. Passaram por uma troca de integrantes em 2013, quando o primeiro Thiago saiu e Paulo Marcel (outro Thiago) assumiu. Com vozes muito afinadas e carisma no palco, conquistaram fãs por todo o Brasil. Já gravaram DVDs em locais paradisíacos e seguem ativos na música sertaneja.',
'Thaeme: 04 de outubro de 1985 / Thiago: 24 de dezembro de 1989',
'Thaeme: Presidente Prudente - SP / Thiago: Ilha Solteira - SP',
'2011 - Presente',
'Ai Que Dó – 2012 / Coração Apertado – 2015 / Vendinha – 2018',
'style/assets/images/fotos_cantores/universitario_dupla/thaeme&thiago.png',
'O Que Acontece Na Balada (feat. Fernando & Sorocaba) - 2014',
'+18 milhões',
'+71 milhões'),
(default, 
'Victor & Leo', 
'style/assets/images/cantor_específico/universitarios_dupla/victor&leo.png',
'Irmãos nascidos em Ponte Nova (MG) e criados em Abre Campo (MG), Victor & Leo revolucionaram o sertanejo no início dos anos 2000, trazendo uma pegada mais acústica e letras poéticas. Lançaram o álbum "Ao Vivo em Uberlândia" (2007), que explodiu no Brasil inteiro. Músicas como “Borboletas” e “Deus e Eu no Sertão” marcaram época. A dupla fez muito sucesso até 2018, quando anunciaram uma pausa para projetos individuais, mas retornaram em 2022. Eles são conhecidos pela mistura de sertanejo, folk, pop e MPB. Victor também se destacou como compositor e produtor de diversos artistas.',
'Victor: 15 de abril de 1975 / Leo: 27 de outubro de 1976',
'Victor: Ponte Nova - MG / Leo: Ponte Nova - MG',
'1992 - 2018 / Retorno 2022 - Presente',
'Fada – 2006 / Deus e Eu no Sertão – 2007 / Nada Normal – 2009',
'style/assets/images/fotos_cantores/universitario_dupla/victor&leo.png',
'Borboletas - 2008',
'+83 milhões',
'+114 milhões'),
(default, 
'Zé Neto & Cristiano', 
'style/assets/images/cantor_específico/universitarios_dupla/zeNeto&cristiano.png',
'A dupla, natural de São José do Rio Preto (SP), começou a ganhar espaço no sertanejo universitário a partir de 2011, mas o sucesso nacional veio em 2016 com o hit “Seu Polícia”. Conhecidos por mesclar sofrência, modão e sertanejo romântico, conquistaram o Brasil inteiro. Suas vozes potentes e afinadas, além de letras emocionantes, os colocaram no topo do sertanejo atual. Emplacaram uma sequência de hits que dominaram rádios, streamings e redes sociais. A dupla é famosa também pela conexão com os fãs e pela simplicidade. Atualmente são referência no sertanejo de “sofrência”.',
'Zé Neto: 09 de fevereiro de 1990 / Cristiano: 09 de janeiro de 1988',
'Zé Neto: São José do Rio Preto - SP / Cristiano: São José do Rio Preto - SP',
'2011 - Presente',
'Você Beija Bem – 2015 / Seu Polícia – 2016 / Largado às Traças – 2018',
'style/assets/images/fotos_cantores/universitario_dupla/zeNeto&cristiano.png',
'Notificação Preferida - 2018',
'+339 milhões',
'+923 milhões');

select * from artistas;

select * from artistas where nome = 'Cristiano Araújo';

SELECT DATE_FORMAT(dtNasc , '%d de %m de %y') FROM artistas  WHERE nome = "Cristiano Araújo";
